/** Column order matches templates/property-import-template.xlsx (DBMS Templates). */
export const PROPERTY_EXCEL_HEADERS = [
  'Portfolio',
  'Service Type',
  'Property Name',
  'Property Identifier',
  'Expedia ID',
  'Expedia Service Fee',
  'Expedia Billing Type',
  'Expedia Service Type',
  'Expedia Frequency',
  'Expedia Priority',
  'Expedia Access Level',
  'Expedia From',
  'Expedia To',
  'From DB',
  'To DB',
  'Expedia Revised Date',
  'Expedia Scheduler Review From',
  'Expedia Scheduler Review To',
  'Expedia Scheduler Review DB From',
  'Expedia Scheduler Review DB To',
  'Expedia CRS',
  'Expedia CRS DB',
  'Expedia Run Date From',
  'Expedia Run Date To',
  'Expedia Run Date DB From',
  'Expedia Run Date DB To',
  'Expedia Scheduler',
  'Expedia Duration',
  'Expedia DB Duration',
  'Expedia Processor',
  'Expedia Username',
  'Expedia Password',
  'Expedia Secondary Username',
  'Expedia Secondary Password',
  'Expedia Credential Verified',
  'Expedia OTP Number',
  'Need Another Domain',
  'Booking ID',
  'Booking Service Fee',
  'Booking Service Type',
  'Booking Frequency',
  'Booking Access Level',
  'Booking From',
  'Booking To',
  'Booking Scheduler',
  'Booking Duration',
  'Booking Processor',
  'Booking Username',
  'Booking Password',
  'Booking Credential Verified',
  'Booking OTP Phone',
  'Agoda ID',
  'Agoda Service Fee',
  'Agoda Service Type',
  'Agoda Frequency',
  'Agoda Access Level',
  'Agoda From',
  'Agoda To',
  'Agoda Scheduler',
  'Agoda Duration',
  'Agoda Processor',
  'Agoda Username',
  'Agoda Password',
  'Agoda Credential Verified',
  'Property Address',
  'Portfolio Contact Email',
  'Reporting Contact',
  'Case Contact Email',
  'Access Contact',
  'Sales Rep',
  'Card Descriptor',
  'Qp Username',
  'Qp Password',
  'FP Username',
  'FP Password'
] as const

function formatCell(value: unknown): string | number {
  if (value === null || value === undefined) return ''
  if (typeof value === 'boolean') return value ? 'Yes' : 'No'
  return value as string | number
}

export function mapPropertyToExcelRow(property: any): Record<string, string | number> {
  const cred = property.credentials?.[0] || {}

  return {
    Portfolio: property.portfolio?.name ?? '',
    'Service Type': property.service_type ?? '',
    'Property Name': property.name ?? '',
    'Property Identifier': property.property_identifier ?? '',
    'Expedia ID': property.expedia_id ?? '',
    'Expedia Service Fee': property.expedia_service_fee ?? '',
    'Expedia Billing Type': property.expedia_billing_type ?? '',
    'Expedia Service Type': property.expedia_service_type ?? '',
    'Expedia Frequency': property.expedia_frequency ?? '',
    'Expedia Priority': property.expedia_priority ?? '',
    'Expedia Access Level': formatCell(property.expedia_access_level),
    'Expedia From': property.expedia_from ?? '',
    'Expedia To': property.expedia_to ?? '',
    'From DB': property.from_db ?? '',
    'To DB': property.to_db ?? '',
    'Expedia Revised Date': property.expedia_revised_date ?? '',
    'Expedia Scheduler Review From': property.expedia_scheduler_review_from ?? '',
    'Expedia Scheduler Review To': property.expedia_scheduler_review_to ?? '',
    'Expedia Scheduler Review DB From': property.expedia_scheduler_review_db_from ?? '',
    'Expedia Scheduler Review DB To': property.expedia_scheduler_review_db_to ?? '',
    'Expedia CRS': property.expedia_crs ?? '',
    'Expedia CRS DB': property.expedia_crs_db ?? '',
    'Expedia Run Date From': property.expedia_run_date_from ?? '',
    'Expedia Run Date To': property.expedia_run_date_to ?? '',
    'Expedia Run Date DB From': property.expedia_run_date_db_from ?? '',
    'Expedia Run Date DB To': property.expedia_run_date_db_to ?? '',
    'Expedia Scheduler': formatCell(property.expedia_scheduler),
    'Expedia Duration': property.expedia_duration ?? '',
    'Expedia DB Duration': property.expedia_db_duration ?? '',
    'Expedia Processor': property.expedia_processor ?? '',
    'Expedia Username': cred.expediaUsername ?? '',
    'Expedia Password': cred.expediaPassword ?? '',
    'Expedia Secondary Username': cred.expediaSecondaryUsername ?? '',
    'Expedia Secondary Password': cred.expediaSecondaryPassword ?? '',
    'Expedia Credential Verified': formatCell(property.expedia_credential_verified),
    'Expedia OTP Number': property.expedia_otp_number ?? '',
    'Need Another Domain': formatCell(property.need_another_domain),
    'Booking ID': property.booking_id ?? '',
    'Booking Service Fee': property.booking_service_fee ?? '',
    'Booking Service Type': property.booking_service_type ?? '',
    'Booking Frequency': property.booking_frequency ?? '',
    'Booking Access Level': formatCell(property.booking_access_level),
    'Booking From': property.booking_from ?? '',
    'Booking To': property.booking_to ?? '',
    'Booking Scheduler': formatCell(property.booking_scheduler),
    'Booking Duration': property.booking_duration ?? '',
    'Booking Processor': property.booking_processor ?? '',
    'Booking Username': cred.bookingUsername ?? '',
    'Booking Password': cred.bookingPassword ?? '',
    'Booking Credential Verified': formatCell(property.booking_credential_verified),
    'Booking OTP Phone': property.booking_otp_phone ?? '',
    'Agoda ID': property.agoda_id ?? '',
    'Agoda Service Fee': property.agoda_service_fee ?? '',
    'Agoda Service Type': property.agoda_service_type ?? '',
    'Agoda Frequency': property.agoda_frequency ?? '',
    'Agoda Access Level': formatCell(property.agoda_access_level),
    'Agoda From': property.agoda_from ?? '',
    'Agoda To': property.agoda_to ?? '',
    'Agoda Scheduler': formatCell(property.agoda_scheduler),
    'Agoda Duration': property.agoda_duration ?? '',
    'Agoda Processor': property.agoda_processor ?? '',
    'Agoda Username': cred.agodaUsername ?? '',
    'Agoda Password': cred.agodaPassword ?? '',
    'Agoda Credential Verified': formatCell(property.agoda_credential_verified),
    'Property Address': property.hotel_address ?? '',
    'Portfolio Contact Email': property.portfolio_contact_email ?? '',
    'Reporting Contact': property.reporting_contact ?? '',
    'Case Contact Email': property.primary_case_email ?? '',
    'Access Contact': property.access_contact ?? '',
    'Sales Rep': property.sales_rep ?? '',
    'Card Descriptor': property.card_descriptor ?? '',
    'Qp Username': property.qp_username ?? '',
    'Qp Password': property.qp_password ?? '',
    'FP Username': property.fp_username ?? '',
    'FP Password': property.fp_password ?? ''
  }
}
