export function mapPropertyToExcelRow(property: any): Record<string, any> {
  const cred = property.credentials?.[0] || {}
  return {
    // ── General ──────────────────────────────────────────────────────────
    'Portfolio': property.portfolio?.name ?? '',
    'Service Type': property.service_type ?? '',
    'Property Name': property.name ?? '',
    'Sales Rep': property.sales_rep ?? '',

    // ── Expedia ──────────────────────────────────────────────────────────
    'Expedia ID': property.expedia_id ?? '',
    'Expedia Billing Type': property.expedia_billing_type ?? '',
    'Expedia Service Type': property.expedia_service_type ?? '',
    'Expedia Frequency': property.expedia_frequency ?? '',
    'Expedia Access Level Verified': property.expedia_access_level != null ? String(property.expedia_access_level) : '',
    'Expedia Historical Review': '',
    'Expedia Scheduler': property.expedia_scheduler != null ? String(property.expedia_scheduler) : '',
    'Expedia Reporting': property.expedia_duration ?? '',
    'DB Duration': property.expedia_db_duration ?? '',
    'Expedia Processor': property.expedia_processor ?? '',
    'Expedia Service Fee': property.expedia_service_fee ?? '',
    'Expedia Priority': property.expedia_priority ?? '',
    'Expedia CRS': property.expedia_crs ?? '',
    'DB CRS': property.expedia_crs_db ?? '',
    'Expedia Run Date From': property.expedia_run_date_from ?? '',
    'Expedia Run Date To': property.expedia_run_date_to ?? '',
    'Expedia Run Date DB From': property.expedia_run_date_db_from ?? '',
    'Expedia Run Date DB To': property.expedia_run_date_db_to ?? '',
    'Expedia Revised Date': property.expedia_revised_date ?? '',
    'Expedia Scheduler Review From': property.expedia_scheduler_review_from ?? '',
    'Expedia Scheduler Review To': property.expedia_scheduler_review_to ?? '',
    'DB Scheduler': property.expedia_scheduler_db ?? '',
    'Expedia Scheduler Review DB From': property.expedia_scheduler_review_db_from ?? '',
    'Expedia Scheduler Review DB To': property.expedia_scheduler_review_db_to ?? '',
    'Expedia Credential Verified': property.expedia_credential_verified != null ? String(property.expedia_credential_verified) : '',
    'Expedia OTP Number': property.expedia_otp_number ?? '',
    'Historical Review (From)': property.from ?? '',
    'Historical Review (From) DB': property.from_db ?? '',
    'User Name Expedia': cred.expediaUsername ?? '',
    'Password Expedia': cred.expediaPassword ?? '',
    'Expedia Secondary User Name': cred.expediaSecondaryUsername ?? '',
    'Expedia Secondary Password': cred.expediaSecondaryPassword ?? '',

    // ── Booking.com ───────────────────────────────────────────────────────
    'Need another Domain': property.need_another_domain != null ? String(property.need_another_domain) : '',
    'Booking ID': property.booking_id ?? '',
    'Booking Service Type': property.booking_service_type ?? '',
    'Booking Frequency': property.booking_frequency ?? '',
    'Booking Access Level Verified': property.booking_access_level != null ? String(property.booking_access_level) : '',
    'Booking Historical Review': '',
    'Booking Scheduler': property.booking_scheduler != null ? String(property.booking_scheduler) : '',
    'Booking Reporting': property.booking_duration ?? '',
    'Booking Processor': property.booking_processor ?? '',
    'Booking Service Fee': property.booking_service_fee ?? '',
    'Booking Priority': property.booking_priority ?? '',
    'Booking CRS': property.booking_crs ?? '',
    'Booking Run Date': property.booking_run_date ?? '',
    'Booking Revised Date': property.booking_revised_date ?? '',
    'Booking Credential Verified': property.booking_credential_verified != null ? String(property.booking_credential_verified) : '',
    'Booking OTP Number': property.booking_otp_number ?? '',
    'Booking OTP Phone Number': property.booking_otp_phone ?? '',
    'User Name Booking': cred.bookingUsername ?? '',
    'Password Booking': cred.bookingPassword ?? '',

    // ── Agoda ────────────────────────────────────────────────────────────
    'Agoda ID': property.agoda_id ?? '',
    'Agoda Service Type': property.agoda_service_type ?? '',
    'Agoda Frequency': property.agoda_frequency ?? '',
    'Agoda Access Level Verified': property.agoda_access_level != null ? String(property.agoda_access_level) : '',
    'Agoda Historical Review': '',
    'Agoda Scheduler': property.agoda_scheduler != null ? String(property.agoda_scheduler) : '',
    'Agoda Reporting': property.agoda_duration ?? '',
    'Agoda Processor': property.agoda_processor ?? '',
    'Agoda Service Fee': property.agoda_service_fee ?? '',
    'Agoda Priority': property.agoda_priority ?? '',
    'Agoda CRS': property.agoda_crs ?? '',
    'Agoda Run Date': property.agoda_run_date ?? '',
    'Agoda Revised Date': property.agoda_revised_date ?? '',
    'Agoda Credential Verified': property.agoda_credential_verified != null ? String(property.agoda_credential_verified) : '',
    'Agoda OTP Number': property.agoda_otp_number ?? '',
    'User Name Agoda': cred.agodaUsername ?? '',
    'Password Agoda': cred.agodaPassword ?? '',

    // ── Contacts & Payment ────────────────────────────────────────────────
    'Hotel Address': property.hotel_address ?? '',
    'Portfolio Contact Email': property.portfolio_contact_email ?? '',
    'Reporting Contact': property.reporting_contact ?? '',
    'Case Contact Email': property.primary_case_email ?? '',
    'Access Contact': property.access_contact ?? '',
    'Card Descriptor': property.card_descriptor ?? '',
    'QP Username': property.qp_username ?? '',
    'QP Password': property.qp_password ?? '',
    'FP User Name': property.fp_username ?? '',
    'FP Password': property.fp_password ?? ''
  }
}
